# Generated by Django 5.2 on 2025-05-17 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_points', models.IntegerField(default=0)),
                ('userr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('book_id', models.TextField()),
                ('desc', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='media/')),
                ('pdf_link', models.TextField()),
                ('bookss', models.ManyToManyField(blank=True, related_name='books', to='mainapp.userprofile')),
            ],
        ),
    ]
