# Generated by Django 5.2.1 on 2025-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='USERNAME_FIELD',
            field=models.TextField(default='nuill'),
        ),
    ]
