# Generated by Django 5.2.1 on 2025-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userprofile_username_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='USERNAME_FIELD',
            field=models.CharField(default='nuill'),
        ),
    ]
