# Generated by Django 5.2.1 on 2025-06-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userprofile_email_alter_userprofile_username_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='USERNAME_FIELD',
        ),
    ]
